# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
Nitroterm.Backend.json:
  no-empty-servers:
    - '#/openapi'
  info-license:
    - '#/info'
  operation-operationId:
    - '#/paths/~1api~1nitroterm~1v1~1auth~1validate/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1register/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1login/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1password/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1logout/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1feed/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1feed~1mine/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1post/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/put/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/delete/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}~1nitronize/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}~1dynamite/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1products/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1products/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1product~1{id}/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1products~1query~1{input}/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}~1follow/post/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}~1picture/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1user/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1user/put/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1user~1picture/get/operationId'
    - '#/paths/~1api~1nitroterm~1v1~1user~1picture/post/operationId'
  operation-summary:
    - '#/paths/~1api~1nitroterm~1v1~1auth~1validate/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1register/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1login/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1password/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1logout/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1feed/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1feed~1mine/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1post/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/put/summary'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/delete/summary'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}~1nitronize/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}~1dynamite/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1products/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1products/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1product~1{id}/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1products~1query~1{input}/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}~1follow/post/summary'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}~1picture/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1user/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1user/put/summary'
    - '#/paths/~1api~1nitroterm~1v1~1user~1picture/get/summary'
    - '#/paths/~1api~1nitroterm~1v1~1user~1picture/post/summary'
  operation-4xx-response:
    - '#/paths/~1api~1nitroterm~1v1~1auth~1validate/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1register/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1login/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1password/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1auth~1logout/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1feed/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1feed~1mine/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1post/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/put/responses'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}/delete/responses'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}~1nitronize/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1posts~1{id}~1dynamite/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1products/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1products/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1product~1{id}/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1products~1query~1{input}/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}~1follow/post/responses'
    - '#/paths/~1api~1nitroterm~1v1~1users~1{username}~1picture/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1user/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1user/put/responses'
    - '#/paths/~1api~1nitroterm~1v1~1user~1picture/get/responses'
    - '#/paths/~1api~1nitroterm~1v1~1user~1picture/post/responses'
